package org.shiftone.jrat.core.command;

import java.io.OutputStream;
import org.shiftone.jrat.core.spi.Commandlet;
import org.shiftone.jrat.util.log.Logger;

/**
 * dumps system propeties.
 *
 * @author jeff@shiftone.org (Jeff Drost)
 */
public class SystemPropertiesCommandlet implements Commandlet {

    private static final Logger LOG = Logger.getLogger(SystemPropertiesCommandlet.class);

    @Override
    public void execute(OutputStream output) throws Exception {
        System.getProperties().store(output, "Generated by " + getClass().getName());
    }

    @Override
    public String getContentType() {
        return Commandlet.ContentType.PLAIN;
    }

    @Override
    public String getTitle() {
        return "Dump System Properties";
    }
}
